### ISSUE TITLE
rework

### ISSUE THREAD

**Issue by remyvanlis** [Jazzmoon/btd6_autoplay#11]
Hello there,

I have made a ton of changes to the behaviour and functionality of the bot. I have made a privately forked repository to do so, and had an extra tester to ensure everything worked as expected.

Just now I have made the repository public, including allowing contributions. This seems kind of unfair, so I think it would be nice if I could push my changes to this branch (perhaps have a look at it together) and see if these are changes you would want in the bot.

https://github.com/remyvanlis/btd6-bot

If you don't want me to keep this repository public, please respond to this issue. I absolutely respect your wishes if you'd rather have it remain private.

**Comment by AstroCoding** [comment]
Hey @remyvanlis,

Seeing how we don't really maintain this tool any more, you are more than welcome to host your own version on your own GitHub account. You credit us in the ReadMe, which is more than kind.

I was thinking about testing this version of the code tomorrow to see if it is Linux friendly, as that was a major downside of the current version at the moment. If it is, we would be interested in making a dedicated branch here on the repo with your code. This branch would still credit you for the work, seeing as it is partly yours after all. We just want to make sure no one is stepping on anyone else's toes.

Please feel free to keep your repo public though. Once we have gone through testing, we can look into adding you as a developer to a dedicate branch here on the project if that is what you are interested in. Or, you could decide to simply keep it on your own GitHub account. That is totally fine with us.

Have a great night,
Astro
